version: '3'
services:
  smap:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: smap
    working_dir: '/app'
    tty: true
    ports: 
      - '8080:8080'
    command: python manage.py runserver 8080