version: '3'
services:
  smap:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: smap
    working_dir: '/app'
    tty: true
    ports: 
      - '8080:8080'
    command: /bin/bash -c "python /app/dashboard/manage.py makemigrations && python /app/dashboard/manage.py migrate && python /app/dashboard/manage.py import && python /app/dashboard/manage.py runserver 0:8080"